applications_open: false
applications_open_when: early 2027
contact_email: hello@goodquestioncamp.com
instagram_url: https://www.instagram.com/campgoodquestion/
facebook_url: https://www.facebook.com/goodquestioncamp
slide_seconds: 3
